#if defined _inc_header
	#undef _inc_header
#endif

new playerOpenCraftingMenu[MAX_PLAYERS];
new playerOpenCraftingCategory[MAX_PLAYERS];
new playerOpenCraftingItem[MAX_PLAYERS];
new playerOpenCraftingDetailItem[MAX_PLAYERS];
new playerGetCraftingType[MAX_PLAYERS];
new playerSelectCategoryID[MAX_PLAYERS];
new playerCraftingPages[MAX_PLAYERS];
new playerCraftingCurrentPages[MAX_PLAYERS];
new playerCraftingMaxPages[MAX_PLAYERS];
new playerClickCraftItemRows[MAX_PLAYERS];
new playerClickCraftItemColumn[MAX_PLAYERS];
new playerClickCraftItemGetID[MAX_PLAYERS];
new playerCraftingItemAmount[MAX_PLAYERS];
new playerStartCraftingItem[MAX_PLAYERS];
