#if defined _inc_impl
	#undef _inc_impl
#endif

LoadObjectGarden(){
    tmpobjid = CreateDynamicObject(882, -306.495239, -1430.988891, 13.705125, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -311.255249, -1430.988891, 13.705125, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -316.245635, -1430.988891, 13.705125, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -321.366149, -1430.988891, 13.705125, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -326.965606, -1430.988891, 13.705125, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(1568, -333.384948, -1433.671264, 14.162021, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(1568, -306.155029, -1433.671264, 13.832015, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(8229, -333.587066, -1424.574951, 15.912515, 0.000000, 0.000000, 84.799934, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -326.585479, -1425.027465, 13.705125, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(8229, -332.516601, -1412.815673, 15.162500, 0.000000, 0.000000, 84.799934, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(8229, -320.569458, -1402.796630, 15.092494, 0.000000, 0.000000, 354.799926, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(8229, -313.598327, -1403.429321, 15.092494, 0.000000, 0.000000, 354.799926, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -320.985717, -1425.027465, 13.705125, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -315.935852, -1425.027465, 13.545123, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(8229, -303.639801, -1415.479858, 15.092494, 0.000000, 0.000000, 624.799926, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(8229, -304.560607, -1424.825439, 15.092494, 0.000000, 0.000000, 624.799926, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -310.875946, -1425.027465, 13.505122, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -306.315887, -1425.027465, 13.445119, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(8229, -323.523254, -1436.466064, 15.912515, 0.000000, 0.000000, 174.799926, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -306.055694, -1418.822998, 13.215115, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -310.846008, -1419.013183, 13.255116, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -315.486145, -1418.863037, 13.255118, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -320.596221, -1418.863037, 13.305117, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -326.586486, -1418.822998, 13.415120, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(1568, -303.354919, -1408.000976, 12.372009, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(1568, -331.164886, -1407.360595, 12.302006, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -326.586486, -1412.601562, 12.945109, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -320.606719, -1412.601562, 12.995112, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -315.246673, -1412.601562, 13.015111, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -310.666656, -1412.601562, 13.015111, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    tmpobjid = CreateDynamicObject(882, -305.696594, -1412.601562, 13.025122, 0.000000, 0.000000, 0.000000, -1, -1, -1, 200.00, 200.00); 
    return 1;
}

ResetGardener(playerid){
    StartGardenerJob[playerid] = false;
    GardenerPoint[playerid] = 0;
    GardenerCount[playerid] = 0;
    CheckLastRamdomGardener[playerid] = -1;
    CheckPlayerEnterPointGarden[playerid] = false;
    FinishGardener[playerid] = false;
    StartingWater[playerid] = false;
    KillTimer(GardenerTime[playerid]);
    GardenerTime[playerid] = 0;
    return 1;
}

StartJobGardener(playerid){
    if(StartGardenerJob[playerid] == 0){
        StartGardenerJob[playerid] = 1;
        if(PlayerData[playerid][pGender] == 1) SetPlayerSkin(playerid, 133);
        else if(PlayerData[playerid][pGender] == 2) SetPlayerSkin(playerid, 131);
        RemoveAttachedObject(playerid, 8);
        RemoveAttachedObject(playerid, 9);
        SetPlayerAttachedObject(playerid,9,19621,6,0.000000,0.000000,0.000000,88.299987,75.300010,108.899978,1.430999,1.334000,1.372999);
        SendClientMessage(playerid, COLOR_YELLOW, "- คุณได้เปลี่ยนชุดและรับอุปกรณ์สำหรับคนดูแลสวนแล้ว, ไปยังจุดสีแดงเพื่อเริ่มทำงาน");
        new rand = random(sizeof(RamdomPointGarden));
        CheckLastRamdomGardener[playerid] = rand;
        SetPlayerCheckpoint(playerid, RamdomPointGarden[rand][0], RamdomPointGarden[rand][1], RamdomPointGarden[rand][2], 1.5);
        CheckPlayerEnterPointGarden[playerid] = true;
    }
    else if(StartGardenerJob[playerid] == 1){
        StartGardenerJob[playerid] = 0;
        SetPlayerSkin(playerid, PlayerData[playerid][pSkin]);
        RemoveAttachedObject(playerid, 8);
        RemoveAttachedObject(playerid, 9);
        ClearAnimations(playerid);
        SetPlayerSpecialAction(playerid, SPECIAL_ACTION_NONE);
        TogglePlayerControllable(playerid, 1);
        ResetGardener(playerid);
        DisablePlayerCheckpoint(playerid);
        SendClientMessage(playerid, COLOR_YELLOW, "- คุณได้เลิกงาน คนดูแลสวน แล้ว");
    }
    return 1;
}

SendGardener(playerid){
    if(GardenerCount[playerid] >= MAX_POINTGARDENER){
        new deliverid = -1;
        if((deliverid = Job_NearestPoint2(playerid)) != -1){
            if(JobData[deliverid][jobType] == GARDENER){
                GardenerPoint[playerid] = 0;
                GardenerCount[playerid] = 0;
                FinishGardener[playerid] = false;
                DisablePlayerCheckpoint(playerid);
                SendClientMessageEx(playerid, COLOR_YELLOW, "- คุณได้รับเงินจากการดูแลสวนครั้งนี้เป็นเงิน %s", FormatNumber(JobData[deliverid][jobDeliverPrice]));
                GiveMoney(playerid, JobData[deliverid][jobDeliverPrice], "get gardener");
                SendClientMessageEx(playerid, COLOR_YELLOW, "[!]: หากคุณต้องทำงานต่อให้ไปยังจุดสีแดงเพื่อทำงานอีกครั้ง, หากไม่ต้องการทำให้เก็บอุปกรณ์และชุดที่จุดเริ่มทำงาน");
                new rand = random(sizeof(RamdomPointGarden));
                SetPlayerCheckpoint(playerid, RamdomPointGarden[rand][0], RamdomPointGarden[rand][1], RamdomPointGarden[rand][2], 1.5);
                CheckLastRamdomGardener[playerid] = rand;
                CheckPlayerEnterPointGarden[playerid] = true;
                PlayerData[playerid][pStress]++;
                if(PlayerData[playerid][pStress] >= 200) PlayerData[playerid][pStress] = 200;
            }
        }
    }
    return 1;
}

forward UpdateGardener(playerid);
public UpdateGardener(playerid){
    if(LoggedIn[playerid]){
        new string[128];
        if(PlayerData[playerid][pJob] == GARDENER){
            if(StartGardenerJob[playerid] == 1 && StartingWater[playerid]){
                if(GardenerPoint[playerid] < 100){
                    GardenerPoint[playerid]++;
                    SetPlayerProgressBarValue(playerid, ProgressbarJob[playerid], GardenerPoint[playerid]);
                    format(string,sizeof(string),"Watering... (%d)", GardenerPoint[playerid]);
                    PlayerTextDrawSetString(playerid, PlayerTextDrawJob[playerid], string);
                    //GameTextForPlayer(playerid, string, 100, 3);
                    GardenerTime[playerid] = SetTimerEx("UpdateGardener", 100, false, "i", playerid);
                }
                else if(GardenerPoint[playerid] >= 100){
                    KillTimer(GardenerTime[playerid]);
                    GardenerTime[playerid] = 0;
                    StartingWater[playerid] = false;
                    ClearAnimations(playerid);
                    RemoveAttachedObject(playerid, 8);
                    DestroyPlayerProgressbar_Job(playerid);
                    TogglePlayerControllable(playerid, 1);
                    new rand = random(sizeof(RamdomPointGarden));

                    if(rand == CheckLastRamdomGardener[playerid]){
                        rand = random(sizeof(RamdomPointGarden));
                        SetPlayerCheckpoint(playerid, RamdomPointGarden[rand][0], RamdomPointGarden[rand][1], RamdomPointGarden[rand][2], 1.5);
                        CheckPlayerEnterPointGarden[playerid] = true;
                        CheckLastRamdomGardener[playerid] = rand;
                    }
                    else if(rand != CheckLastRamdomGardener[playerid]){
                        SetPlayerCheckpoint(playerid, RamdomPointGarden[rand][0], RamdomPointGarden[rand][1], RamdomPointGarden[rand][2], 1.5);
                        CheckPlayerEnterPointGarden[playerid] = true;
                        CheckLastRamdomGardener[playerid] = rand;
                    }
                    
                    GardenerCount[playerid]++;

                    SendClientMessageEx(playerid, COLOR_YELLOW, "- ไปยังจุดต่อไปเพื่อรดน้ำดอกไม้ [%d/%d]", GardenerCount[playerid], MAX_POINTGARDENER);

                    if(GardenerCount[playerid] >= MAX_POINTGARDENER){
                        new id = GetClosestJobPoint2(playerid, PlayerData[playerid][pJob]);
                        if (id != -1)
                        {
                            if(JobData[id][jobPoint2][0] == 0.0 && JobData[id][jobPoint2][1] == 0.0 && JobData[id][jobPoint2][2] == 0.0)
                                return ErrorMsg(playerid, "ไม่สามารถค้นหาจุดนี้ได้");

                            FinishGardener[playerid] = true;

                            SetPlayerCheckpoint(playerid, JobData[id][jobPoint2][0], JobData[id][jobPoint2][1], JobData[id][jobPoint2][2], 2.0);
                            SendClientMessage(playerid, -1,"คุณได้เปิด GPS ไปยัง จุดส่งงานคนดูแลสวน");
                        }
                    }
                }
            }
        }
    }
    return 1;
}