#if defined _inc_header
	#undef _inc_header
#endif

#include "buildjob\header"
#include "clothjob\header"
#include "cowjob\header"
#include "deliveroiljob\header"
#include "engineerjob\header"
#include "farmerjob\header"
#include "fishjob\header"
#include "garbagejob\header"
#include "gardenerjob\header"
#include "gasjob\header"
#include "jellyfishjob\header"
#include "oiljob\header"
#include "orangejob\header"
#include "pizzajob\header"
#include "rubberjob\header"
#include "seekerjob\header"
#include "sharkjob\header"
#include "shelljob\header"
#include "weapondealerjob\header"