#if defined _inc_impl
	#undef _inc_impl
#endif

#include "buildjob\impl"
#include "clothjob\impl"
#include "cowjob\impl"
#include "deliveroiljob\impl"
#include "engineerjob\impl"
#include "farmerjob\impl"
#include "fishjob\impl"
#include "garbagejob\impl"
#include "gardenerjob\impl"
#include "gasjob\impl"
#include "jellyfishjob\impl"
#include "oiljob\impl"
#include "orangejob\impl"
#include "pizzajob\impl"
#include "rubberjob\impl"
#include "seekerjob\impl"
#include "sharkjob\impl"
#include "shelljob\impl"
#include "weapondealerjob\impl"