#if defined _inc_header
	#undef _inc_header
#endif

new PlayerQuestAccept[MAX_PLAYERS];
new PlayerQuestState[MAX_PLAYERS];

new PlayerQuest_Count2[MAX_PLAYERS];
new PlayerQuest_Count3[MAX_PLAYERS];
new PlayerQuest_Count4[MAX_PLAYERS];
new PlayerQuest_Count5[MAX_PLAYERS];
new PlayerQuest_Count6[MAX_PLAYERS];
new PlayerQuest_Count7[MAX_PLAYERS];
new PlayerQuest_Count8[MAX_PLAYERS];
new PlayerQuest_Count9[MAX_PLAYERS];
new PlayerQuest_Count10[MAX_PLAYERS];
new PlayerQuest_Count11[MAX_PLAYERS];
new PlayerQuest_Count12[MAX_PLAYERS];
new PlayerQuest_Count13[MAX_PLAYERS];