#if defined _inc_header
	#undef _inc_header
#endif

new PlayerGetPow[MAX_PLAYERS];
new PlayerGetPricePow[MAX_PLAYERS];
new PlayerGetIDPow[MAX_PLAYERS];

new CraftWeaponTimer[MAX_PLAYERS];
new CraftWeaponPoint[MAX_PLAYERS];
new StartingCraftWeapon[MAX_PLAYERS];

new PlayerOpenCraftWeaponMenu[MAX_PLAYERS];
new PlayerOpenCraftWeaponInfoMenu[MAX_PLAYERS];
new PlayerGetIndexWeaponCraft[MAX_PLAYERS];

new PlayerOpenMenuTime[MAX_PLAYERS];